export type StaticRebrickableCategory = {
	id: number;
	name: string;
	part_count: number;
};

export const staticRebrickableCategories: StaticRebrickableCategory[] = [
	{ id: 74, name: "Animal / Creature Accessories", part_count: 70 },
	{ id: 75, name: "Animal / Creature Body Parts", part_count: 928 },
	{ id: 28, name: "Animals / Creatures", part_count: 861 },
	{ id: 32, name: "Bars, Ladders and Fences", part_count: 134 },
	{ id: 1, name: "Baseplates", part_count: 243 },
	{ id: 42, name: "Belville, Scala and Fabuland", part_count: 737 },
	{ id: 11, name: "Bricks", part_count: 1742 },
	{ id: 37, name: "Bricks Curved", part_count: 896 },
	{ id: 20, name: "Bricks Round and Cones", part_count: 578 },
	{ id: 3, name: "Bricks Sloped", part_count: 614 },
	{ id: 5, name: "Bricks Special", part_count: 318 },
	{ id: 6, name: "Bricks Wedged", part_count: 319 },
	{ id: 48, name: "Clikits", part_count: 413 },
	{ id: 7, name: "Containers", part_count: 192 },
	{ id: 4, name: "Duplo, Quatro and Primo", part_count: 5130 },
	{ id: 45, name: "Electronics", part_count: 552 },
	{ id: 69, name: "Energy Effects", part_count: 94 },
	{ id: 38, name: "Flags, Banners and Signs", part_count: 386 },
	{ id: 17, name: "Gear Parts", part_count: 3943 },
	{ id: 18, name: "Hinges, Arms and Turntables", part_count: 240 },
	{ id: 50, name: "HO Scale", part_count: 103 },
	{ id: 41, name: "Large Buildable Figures", part_count: 1398 },
	{ id: 39, name: "Magnets and Holders", part_count: 43 },
	{ id: 44, name: "Mechanical", part_count: 28 },
	{ id: 62, name: "Minidoll Heads", part_count: 451 },
	{ id: 64, name: "Minidoll Lower Body", part_count: 520 },
	{ id: 63, name: "Minidoll Upper Body", part_count: 762 },
	{ id: 27, name: "Minifig Accessories", part_count: 729 },
	{ id: 59, name: "Minifig Heads", part_count: 5190 },
	{ id: 65, name: "Minifig Headwear", part_count: 2151 },
	{ id: 72, name: "Minifig Headwear Accessories", part_count: 155 },
	{ id: 70, name: "Minifig Hipwear", part_count: 128 },
	{ id: 61, name: "Minifig Lower Body", part_count: 3083 },
	{ id: 71, name: "Minifig Neckwear", part_count: 599 },
	{ id: 73, name: "Minifig Shields, Weapons, & Tools", part_count: 553 },
	{ id: 60, name: "Minifig Upper Body", part_count: 7492 },
	{ id: 13, name: "Minifigs", part_count: 586 },
	{ id: 66, name: "Modulex", part_count: 1181 },
	{ id: 57, name: "Non-Buildable Figures (Duplo, Fabuland, etc)", part_count: 1232 },
	{ id: 77, name: "Non-System Parts", part_count: 334 },
	{ id: 24, name: "Other", part_count: 39 },
	{ id: 23, name: "Panels", part_count: 396 },
	{ id: 78, name: "Pen & Watch", part_count: 597 },
	{ id: 76, name: "Plants & Trees", part_count: 133 },
	{ id: 14, name: "Plates", part_count: 135 },
	{ id: 49, name: "Plates Angled", part_count: 78 },
	{ id: 21, name: "Plates Round Curved and Dishes", part_count: 357 },
	{ id: 9, name: "Plates Special", part_count: 466 },
	{ id: 22, name: "Pneumatics", part_count: 34 },
	{ id: 68, name: "Projectiles / Launchers", part_count: 221 },
	{ id: 33, name: "Rock", part_count: 56 },
	{ id: 58, name: "Stickers", part_count: 4462 },
	{ id: 31, name: "String, Bands and Reels", part_count: 132 },
	{ id: 34, name: "Supports, Girders and Cranes", part_count: 93 },
	{ id: 46, name: "Technic Axles", part_count: 27 },
	{ id: 51, name: "Technic Beams", part_count: 50 },
	{ id: 55, name: "Technic Beams Special", part_count: 41 },
	{ id: 8, name: "Technic Bricks", part_count: 28 },
	{ id: 54, name: "Technic Bushes", part_count: 7 },
	{ id: 12, name: "Technic Connectors", part_count: 116 },
	{ id: 52, name: "Technic Gears", part_count: 106 },
	{ id: 40, name: "Technic Panels", part_count: 156 },
	{ id: 53, name: "Technic Pins", part_count: 34 },
	{ id: 26, name: "Technic Special", part_count: 208 },
	{ id: 25, name: "Technic Steering, Suspension and Engine", part_count: 127 },
	{ id: 19, name: "Tiles", part_count: 3380 },
	{ id: 67, name: "Tiles Round and Curved", part_count: 1170 },
	{ id: 15, name: "Tiles Special", part_count: 499 },
	{ id: 56, name: "Tools", part_count: 21 },
	{ id: 36, name: "Transportation - Land", part_count: 549 },
	{ id: 35, name: "Transportation - Sea and Air", part_count: 473 },
	{ id: 30, name: "Tubes and Hoses", part_count: 196 },
	{ id: 29, name: "Wheels and Tyres", part_count: 400 },
	{ id: 16, name: "Windows and Doors", part_count: 473 },
	{ id: 47, name: "Windscreens and Fuselage", part_count: 490 },
	{ id: 43, name: "Znap", part_count: 22 },
];
